src/App.tsx, src/Router.tsx
=> [이재성] 테스트 pr 입니다.

src/pages/Channel.tsx, src/pages/Notify.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx
closes #18 
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> Design:레이아웃 수정

src/components/Header.tsx, src/components/ToggleThemeBtn.tsx
=> Feat:다크모드/라이트모드 구현

src/App.tsx, src/pages/Channel.tsx, src/pages/Notify.tsx, src/pages/SignUp.tsx
어떤 변경 사항이 있나요?
고차컴포넌트와 같은 로직으로 Sidebar 컴포넌트의 너비가 1/6이고 나머지 공간은 Outlet 컴포넌트가 차지하도록 했다.
이를 통해 페이지를 만들 때마다 width를 일일이 설정할 필요 없이, 재사용 가능한 레이아웃 구성을 통해 코드의 유지보수성과 가독성을 향상 시킬 수 있다.
=> Design:Outlet 레이아웃 수정 최종

src/pages/ChannelSettings.tsx, src/pages/SignUp.tsx
=> Design:채널설정페이지,회원가입 폼 변경

package-lock.json, src/components/Header.tsx, src/components/Submenu.tsx, src/pages/Home.tsx, tailwind.config.js
어떤 변경 사항이 있나요?
closed #25 
사이드바 Drawer flowbite 에서 적용시키려고 했으나 단순 Button 정도 수준은 패키지 다운 없이 가능한데
Drawer 같이 복잡한 컴포넌트는 react-tsc 에서 호환되지 않아 보류함
=> [#25] Refactor: etc 

fake-server/db.json, package-lock.json, src/api.ts, src/pages/Subscriptions.tsx, src/types/interface.ts
어떤 변경 사항이 있나요?
closed #30 
구독리스트,구독 기능 구현 및 json-server 세팅
=> Feat:구독리스트 페이지,기능구현

package-lock.json, src/Router.tsx, src/components/Header.tsx, src/components/Submenu.tsx, src/pages/Home.tsx, src/pages/StreamingLive.tsx, src/pages/StreamingSetting.tsx, tailwind.config.js
어떤 변경 사항이 있나요?
closed #29
+ 스트리밍 화면 페이지 UI 구성
+ 스트리밍 하기 전 세팅 페이지 UI 구성
StreamingLive 페이지는 레이아웃만 잡아 놓았음
StreamingSetting 페이지는 useForm을 사용하여 방송 시작 전 세팅값 관리
=> [#29] Feat: Streaming pages

package-lock.json, package.json, src/components/StreamVideo.tsx, src/pages/StreamingLive.tsx, src/pages/StreamingSetting.tsx
어떤 변경 사항이 있나요?
closed #36 
URL HLS (HTTP Live Streaming) 형식의 비디오를 제공하므로 Safari 외에 다른 브라우저에서 호환될 수 있도록
hls.js 라이브러리를 이용한 연동 방식 구현
방송 세팅 부분 useForm 사용에서 useState 변경하여 radio 부분 checkbox로 해결
=> [#36] 라이브 스트리밍 송출 및 세팅 관련 수정

src/pages/Community.tsx, src/pages/CreatePost.tsx, src/pages/PostDetail.tsx, src/pages/UpdatePost.tsx
어떤 변경 사항이 있나요?
closed #39 
커뮤니티 기능 구현,proxy설정
=> Feat/커뮤니티 기능 구현

src/components/Header.tsx, src/pages/Community.tsx, vite.config.ts
어떤 변경 사항이 있나요?
헤더 반응형,검색창 UI 변경,proxy target변경
=> Feat:헤더 반응형

src/api.ts, src/pages/ChannelSettings.tsx
어떤 변경 사항이 있나요?
프로필 이미지 제거 기능 추가,api수정
=> Feat:api수정에 따른 호출 함수 수정,프로필 이미지 제거 추가

src/App.tsx, src/Router.tsx, src/components/Layout.tsx, src/components/ProtectedRoute.tsx, src/main.tsx, src/pages/NotFound.tsx, vite.config.ts
어떤 변경 사항이 있나요?
closed #49 
가독성을 위해 기존의 배열 내의 객체 형식으로 관리하던 라우터 형식을 컴포넌트 형식으로 수정, outlet과 layout을 통해 라우터 관리
=> Refactor/router 변경

src/api.ts, src/pages/Channel.tsx, src/pages/Community.tsx, src/types/interface.ts, src/utils/community/getPosts.ts
어떤 변경 사항이 있나요?
closed #53 
글 생성 수정 삭제 연동, 글 상세보기는 api가 없어서 백엔드에서 만드는 중
=> Feat:게시글 기능 연동

src/api.ts, src/pages/PostDetail.tsx, src/utils/community/getPosts.ts
어떤 변경 사항이 있나요?
게시글 상세 보기 연동 완료 (게시글 기능 전체 완료)
=> feat:게시글 상세보기 연동

src/api.ts, src/components/Submenu.tsx, src/pages/Channel.tsx, src/pages/ChannelSettings.tsx, src/pages/Community.tsx, src/pages/StreamingLive.tsx, src/pages/StreamingSetting.tsx, src/pages/Subscriptions.tsx, src/types/interface.ts
어떤 변경 사항이 있나요?
+ layout 구분을 위한 흰색 border 모두 rounded 한 gray 색상으로 변경
+ 사이드바에서 내 채널, 구독 이동 시 변경된 path에 닉네임 추가하여 수정
+ 사이드바 뮤즈 이동 버튼 삭제
+ 구독 리스트, 추가, 삭제 기능 API 연동
+ channel 페이지에서 채널 주인과 타 유저 간 버튼 기능 구분
자기 채널에서는 구독리스트 구독추가 및 해제 가능
유저가 다른사람 채널 입장 시 해당 유저 구독 및 해제 가능
+ 라이브 스트리밍 페이지에서도 스트리밍 중인 유저 구독 추가 및 해제 기능 구현
=> Feat : 구독 API 연결 및 전체 UI 수정

.gitignore, package-lock.json, package.json, src/api.ts, src/components/Header.tsx, src/components/Modal.tsx, src/pages/Home.tsx, src/pages/Notify.tsx, src/pages/SignIn.tsx, src/pages/SignUp.tsx, src/pages/StreamingLive.tsx, src/store.ts, src/types/interface.ts, src/utils/channelSetting/useUpdateNickname.ts, src/utils/notify/useNotification.ts, src/utils/signIn/useRefreshToken.ts
어떤 변경 사항이 있나요?
closed #62 
+ 실시간 시청자 수 업데이트 연동 (라이브 스트리밍 페이지, 라이브 스트리밍 리스트 페이지)
+ 라이브 스트리밍 시청자수 많은 순으로 리스트업
+ 알람 기능인 usenotification 커스텀 훅 구현
+ 알림 리스트 persist로 관리 및 Header 컴포넌트에서 전역적으로 감시 및 업데이트
+ 로그아웃 시 알림정보 초기화
+ 로그아웃 시 로그인 페이지로 이동
+ 구독한 스트리머가 라이브 스트리밍 시작 시 방송시작 알림 연동
+ 로그인 유저가 바뀔 때 마다 알림 연결(SSE) 갱신
+ 불필요 console.log 삭제
=> Feat: 구독 알람 기능

src/components/Chat.tsx
어떤 변경 사항이 있나요?
스트리밍 방에 입장 했을 때 이전 채팅 내역을 불러오는데, 채팅 내역이 거꾸로 불러져 오고 있는 문제 해결
=> feat:채팅 내역 불러오기 수정

vercel.json
=> Feat: vercel 전용 proxy 설정 추가

src/api.ts
=> Fix: 카테고리 api 오타 수정

src/pages/Subscriptions.tsx
어떤 변경 사항이 있나요?
+ 구독리스트 채널방문 버튼 2개 생기는 오류 수정
=> Fix: 채널 방문 버튼 2개 나타나는 오류 수정

src/utils/streaming/useStreamServer.ts
=> Fix: 배포 시 rtmp 요청 url http -> https로 변경

src/utils/streaming/useStreamServer.ts
어떤 변경 사항이 있나요?
+ https 통신을 위한 스트림서버 url 변경
=> Fix: https 통신을 위한 streamServer URL 변경
